<a href="https://colab.research.google.com/github/Hanjateacherson/SMHRD/blob/main/python/01_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#넘파이 - 고성능 과학계산, 배열연산 배열 생성

# ㄴ 숫자

# 배열이란???
# 리스트 - 다양한 자료형을 나열한 자료형. 인덱스로 접근

# 배열 - 하나의 자료형을 나열하는 자료형, 인덱스로 접근(int, float, str)


In [ ]:
#numpy 사용방법
import numpy as np


In [ ]:
#1차원 배열 생성하기

# 배열 == array
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
list1 = [10,20,30,40,50]
arr2 = np.array(list1)
arr2


array([10, 20, 30, 40, 50])

In [ ]:
#2차원 배열 생성
arr3 = np.array([[1,2,3],[10,20,30]])
arr3


array([[ 1,  2,  3],
       [10, 20, 30]])

In [ ]:
#배열의 속성을 확인해봅시다

#1. 배열의 크기 - 다차원배열의 크기를 알아내는데 유용
#               ㄴ 배열명.shape

#튜플로 return이 됨
arr3.shape #행과 열로 출력

#행만 출력
print(arr3.shape[0])

#열만 출력
print(arr3.shape[1])

2
3


In [ ]:
#2. 차원수 - 해당 배열이 몇 차원인지 알려주는 속성
#          ㄴ 배열명.ndim
print(arr2.ndim) #1차원
print(arr3.ndim)


1
2


In [ ]:
#3. 전체 요소개수 - 해당 배열의 값들의 수를 알려주는 속성
#                 ㄴ .size

print(arr2.size)
print(arr3.size)

5
6


In [ ]:
#4. 데이터 타입 - 요소의 타입을 알려주는 속성
#               ㄴ .dtype
print(arr2.dtype)
print(arr3.dtype)

int64
int64


In [ ]:
#배열 함수들 알아보기


In [ ]:
#1. 0으로 초기화 하는 함수
# .zeros((행,열))
arr_zero =np.zeros((3,4))
arr_zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#2. 1로 초기화 하는 함수
# .ones((행,열))
arr_one = np.ones((3,4))
arr_one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#3. 그 외 수로 초기화 하는 함수
# .full((행,열), 초기화 할 값)
arr_full = np.full((3,4),7)
arr_full #7로

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
#4. 연속 값으로 초기화 하는 함수 - 1차원 배열
# .arange(시작값 , 끝값) # 끝 값은 미만

arr_arange = np.arange(1,51)
arr_arange  # 1부터 50까지의 수


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [ ]:
#4.1 연속 값으로 초기화 하는 함수 - step이 있게
arr_arange2 = np.arange(1,51,10) # 10씩 증가
arr_arange2





array([ 1, 11, 21, 31, 41])

In [ ]:
list2 =[]
for i in range(1,51):
    list2.append(i)
print(list2)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


# numpy 인덱싱, 슬라이싱 - 데이터 접근 및 처리

In [ ]:
#1차원 배열 만들기
arr4 = np.array([10,20,30,40,50,60])
arr4


array([10, 20, 30, 40, 50, 60])

In [ ]:
#인덱싱
# 리스트의 인덱싱 - list명[인덱스 숫자]
# 넘파이의 배열도 동일
# 인덱싱 방법 --> []


print(arr4[3])

#한번에 여러요소를 접근하는 경우 대괄호 한번 더 쓰워주기
print(arr4[[0,4]]) #0번째 4번째


40
[10 50]


### 1차원 슬라이싱

In [ ]:
# 리스트 슬라이싱 - [:]
# 배열도 동일
print(arr4[1:5])
print(arr4[:5])
print(arr4[2:])
print(arr4[:]) #모두

[20 30 40 50]
[10 20 30 40 50]
[30 40 50 60]
[10 20 30 40 50 60]


### 2차원 인덱싱

In [ ]:
 # 1차원 배열을 2차원 배열로 만들어주는 함수
 # .reshape(행,열)
print(arr4)
arr5 = arr4.reshape(2,3)

print(arr5)

[10 20 30 40 50 60]
[[10 20 30]
 [40 50 60]]


In [ ]:
print(arr5[0]) #10,20,30
print(arr5[0][1])

#2차원 배열 데이터 접근하는 방법 1가지 더 존재
#[행,열] - ,(콤마) 기준 앞이 행 뒤가 열
print(arr5[0,1]) #arr5[0][1]와 동일

[10 20 30]
20
20


#### 2차원 슬라이싱

In [ ]:
arr5[:]

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:

arr5[0,:] # 콤마를 기준으로 앞은 행 뒤는 열
#행은 0번째 (인덱싱), 열은 슬라이싱으로 전부 출력

array([10, 20, 30])

In [ ]:
# 20, 30만 출력하고 싶다

print(arr5[0,1:])

# 40, 50
print(arr5[1,:2])

#10,20,40,50
print(arr5[0:2,0:2])

[20 30]
[40 50]
[[10 20]
 [40 50]]


![image.png](attachment:image.png)


In [ ]:
# 모름

arr5[:,[0,2]] #전체행 ,[0번째,2번째]

array([[10, 30],
       [40, 60]])

In [ ]:
# 모름
arr5[:,::2] # [:,::step] step작성

array([[10, 30],
       [40, 60]])

In [ ]:
# 데이터 수정
# 수정하고 싶은 위치 접근 후 대입 -- 인덱싱(슬라이싱) 한 후 = 원하는 변수
# arr5의 0행에 있는 데이터를 모두 100으로 수정
arr5[0] =100
# arr5[0] == arr5[0,:]
arr5

print(arr5)

arr5[0, :] = [10,20,30]
print(arr5)

[[100 100 100]
 [ 40  50  60]]
[[10 20 30]
 [40 50 60]]


In [ ]:
#데이터 추가
# list의 경우  append와 insert
# append(추가할 array, 추가 할 값) - 맨끝에 추가
arr6 = np.append(arr5, 30) # 끝에 30이 추가
arr6

array([10, 20, 30, 40, 50, 60, 30])

In [ ]:
# 데이터 병합
# concatenate
list1= [1,2,3,4,5]
list2 = [10,20,30,40,50]
print(list1+list2) #리스트의 겨우 더할 시 데이터가 병합의 느낌


[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]


In [ ]:
arr7 = np.array([1,2,3,4,5])
arr8 = np.array([10,20,30,40,50])

arr_concat = np.concatenate([arr7,arr8]) #안에 리스트형태로 들어가야한다
arr_concat

array([ 1,  2,  3,  4,  5, 10, 20, 30, 40, 50])

### 조건에 맞는 데이터 접근하기

#### 불리언인덱싱


In [ ]:
bool_arr = [True, False]

#numpy에 있는 random함수
np.random.seed(1) #1번 씨드로 고정
bool_arr1= np.random.choice(bool_arr, size=10)
# True, False의 값을 랜덤으로 10개 만들겠습니다

print(bool_arr1)

temp_arr = np.arange(10)
print(temp_arr)

#temp_arr 불리언 인덱싱
# 불리언 인덱싱 - True인 값들 만 출력
# 불리언 인덱싱 - True, False가 담긴 array를 인덱싱
temp_arr[bool_arr1] # True인 값들 만 출력

[False False  True  True False False False False False  True]
[0 1 2 3 4 5 6 7 8 9]


array([2, 3, 9])

In [ ]:
# 작성한 조건으로 불리언 인덱싱

# 성적데이터를 램덤으로 생성
np.random.seed(7)
score_arr = np.random.randint(50,100, size=20)
display(score_arr)

student_arr = np.arange(1,21)
display(student_arr)

array([97, 54, 75, 53, 69, 73, 89, 78, 64, 73, 58, 75, 96, 92, 76, 58, 89,
       88, 54, 98])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
#논리연산자 사용해서 80점 이상인 학생들만 출력
# <, >, ==, and, or, not, in
score_arr[score_arr >80]

array([97, 89, 96, 92, 89, 88, 98])

In [ ]:
score_arr[score_arr >80].size #7명 #몇 명인지 알려준다

7

In [ ]:
# 성적이 60점 이상인 학생들을 출력
student_arr[score_arr>=60]

array([ 1,  3,  5,  6,  7,  8,  9, 10, 12, 13, 14, 15, 17, 18, 20])

# 배열의 연산

In [ ]:
arr10 = np.array([1,2,3,4,5])
display(arr10)

#연산
arr10 = arr10 +10
display(arr10)

array([1, 2, 3, 4, 5])

array([11, 12, 13, 14, 15])

In [ ]:
arr11 = np.array([1,2,3,4,5])
arr12 = np.array([10,20,30,40,50])

display(arr11+arr12) #인덱스 위치만 맞으면 더해진다


array([11, 22, 33, 44, 55])

In [ ]:
# 파일 불러오기 경로
#delimiter ='구분자'
height_weight_data = np.loadtxt('data/height_weight.txt', delimiter=',')
height_weight_data

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

In [ ]:
# 데이터의 정보 확인
print(height_weight_data.shape) #2행10열의 데이터 (0행-키, 1헹-몸무게)

print(height_weight_data.ndim) #차원

(2, 10)
2


In [ ]:
height = height_weight_data[0]
height

array([175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
       179. ])

In [ ]:
height + 100

array([275.2, 280.3, 275. , 269.2, 285.2, 288. , 277.6, 278.2, 277. ,
       279. ])

![image.png](attachment:image.png)

In [ ]:
m_height = height/100
m_height

array([1.752, 1.803, 1.75 , 1.692, 1.852, 1.88 , 1.776, 1.782, 1.77 ,
       1.79 ])

In [ ]:
# bmi구하기

weight = height_weight_data[1]
display(weight)

array([65.6, 88. , 79.2, 69.3, 55. , 71.2, 73. , 68.9, 74. , 82. ])

In [ ]:
bmi = weight /(m_height**2)
display(bmi)

array([21.37153104, 27.07018468, 25.86122449, 24.20652885, 16.03543423,
       20.14486193, 23.14392095, 21.69720651, 23.62028791, 25.59220998])

## 과체중인 사람만 출력

In [ ]:
bmi >=23

array([False,  True,  True,  True, False, False,  True, False,  True,
        True])

In [ ]:
bmi[(bmi>=23) & (bmi<25)]

array([24.20652885, 23.14392095, 23.62028791])

# Numpy 함수

### 연산에 특화된 함수

##### sum() : 총합함수

In [ ]:
import numpy as ny

In [ ]:
arr1 = np.array([10,20,30,40,50])

# 기존에 리스트

#sum() -- 배열명. sum()
#        ㄴ 배열 내 있는 모든 값을 더해주는 함수
print(arr1.sum()) # 150 모두 더한값

#2번째 - np.sum(배열 명)
print(np.sum(arr1))



150
150


### mean()함수

In [ ]:
# 평균값 구하는 함수
#배열명.mean()
#np.mean(배열명)

print(arr1.mean())
print(np.mean(arr1))

30.0
30.0


### sqrt () -함수 squre root -- 제곱근

In [ ]:
# 제곱근을 구하는 함수 - np.sqrt(배열 명)
arr2 = np.array([4,9,16,25,36])

print(np.sqrt(arr2)) #root값들 출력


[2. 3. 4. 5. 6.]


### abs()함수


In [ ]:
# 절대값 구하는 함수 - np.abs(배열 명)

arr3 = np.array([-1,2,3,-4,5])
print(np.abs(arr3))

[1 2 3 4 5]


### bincount() -값을 카운팅 하는 함수  

In [ ]:
np.random.seed(1)
arr4 = np.random.randint(1,5,size =5)
display(arr4)

array([2, 4, 1, 1, 4])

In [ ]:
#np.bincount(배열명)
np.bincount(arr4)

#결과값은 순서대로 값을 카운팅하여 출력

array([0, 2, 1, 0, 2])

### np.unique: 중복없이 유니크한 값 확인하는 함수

In [ ]:
# np.unique(배열)
print(np.unique(arr4)) # 중복값이 삭제돤 1,2,4만 삭제된다

[1 2 4]


### np.where() :조건에 해당하는 값을 찾고 처리하는 함수

In [ ]:
#매개변수 : 조건 작성
display(arr4)



array([2, 4, 1, 1, 4])

In [ ]:
np.where(arr4 < 2)

(array([2, 3]),)

### 불리언 인덱싱

In [ ]:
bmi

array([21.37153104, 27.07018468, 25.86122449, 24.20652885, 16.03543423,
       20.14486193, 23.14392095, 21.69720651, 23.62028791, 25.59220998])

In [ ]:
bmi>23

array([False,  True,  True,  True, False, False,  True, False,  True,
        True])

In [ ]:
bmi[bmi>23]

array([27.07018468, 25.86122449, 24.20652885, 23.14392095, 23.62028791,
       25.59220998])

In [ ]:
# 데이터 불러오기
rating = np.loadtxt('data/ratings.dat',delimiter='::')

TypeError: ignored

In [ ]:
rating = np.genfromtxt('data/ratings.dat',delimiter='::',dtype = np.int64)
rating

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]])

In [ ]:
rating.dtype

dtype('int64')

### 데이터 정보 확인하기

In [ ]:
print(rating.ndim)
# 차원 수 확인
print(rating.shape)
print(rating.size)

2
(1000209, 4)
4000836


### 인덱싱/슬라이싱

In [ ]:
# 평점 데이터
rating[:,2]

array([5, 3, 3, ..., 5, 4, 4])

In [ ]:
# 평점들의 평균 - mean()
rating_mean = rating[:,2].mean()
print(rating_mean)

3.581564453029317


In [ ]:
# 사용자 id만 접근
rating_id = rating[:,0]
print(rating_id)

[   1    1    1 ... 6040 6040 6040]


In [ ]:
#unique() 함수 사용
# np.unique(배열명, return_counts =True) ⏩ 해당 중복된 값의 개수를 리
unique_id = np.unique(rating_id)
print(unique_id)
print(unique_id.shape)

[   1    2    3 ... 6038 6039 6040]
(6040,)


In [ ]:
np.unique(rating_id, return_counts=True )

(array([   1,    2,    3, ..., 6038, 6039, 6040]),
 array([ 53, 129,  51, ...,  20, 123, 341]))

In [ ]:
# 불리언 인덱싱
# user_id가 1인 사람의 평균평점
# ↪️ 1. user_id 1인 사람 구하기
user_id1 =rating[rating[0:,0]==1]
print(user_id1.shape)
# ↪️ 2. 1인 사람의 평점
user_id1[:,2]
# ↪️ 3. 평점의 평균
user_id1[:2].mean()

(53, 4)


244575591.625

In [ ]:
#user_id ==1
rating[rating[:,0]==1][:,2].mean()

4.188679245283019

In [ ]:
# user_id == 2
rating[rating[:,0]==2]

In [ ]:
# user_id == 3
rating[rating[:,0]==3][:,2].mean()

3.9019607843137254

In [ ]:
user_id = np.unique(rating_id)
user_id

array([   1,    2,    3, ..., 6038, 6039, 6040])

In [ ]:
rating_result = []
for i in user_id:
  rating_mean = rating[rating[:,0]==i][:,2].mean()
  rating_result.append([user_id, rating_mean])
#print(rating_mean)

In [ ]:
print(rating_result)

[[array([   1,    2,    3, ..., 6038, 6039, 6040]), 4.188679245283019], [array([   1,    2,    3, ..., 6038, 6039, 6040]), 3.7131782945736433], [array([   1,    2,    3, ..., 6038, 6039, 6040]), 3.9019607843137254], [array([   1,    2,    3, ..., 6038, 6039, 6040]), 4.190476190476191], [array([   1,    2,    3, ..., 6038, 6039, 6040]), 3.1464646464646466], [array([   1,    2,    3, ..., 6038, 6039, 6040]), 3.9014084507042255], [array([   1,    2,    3, ..., 6038, 6039, 6040]), 4.32258064516129], [array([   1,    2,    3, ..., 6038, 6039, 6040]), 3.884892086330935], [array([   1,    2,    3, ..., 6038, 6039, 6040]), 3.7358490566037736], [array([   1,    2,    3, ..., 6038, 6039, 6040]), 4.114713216957606], [array([   1,    2,    3, ..., 6038, 6039, 6040]), 3.2773722627737225], [array([   1,    2,    3, ..., 6038, 6039, 6040]), 3.8260869565217392], [array([   1,    2,    3, ..., 6038, 6039, 6040]), 3.388888888888889], [array([   1,    2,    3, ..., 6038, 6039, 6040]), 3.32], [array([   1